version = 1
SPDX-PackageName = "backgrounds"
SPDX-PackageSupplier = "SAP Mac Open Source Security macatsap-opensource-security@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/SAP/backgrounds"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and backgrounds contributors."
SPDX-License-Identifier = "Apache-2.0"
